### PR TITLE
Catalog of my things Ruby Capstone Project Complete

### PR DESCRIPTION
**Pull request by MarcoOquendoC**
# Hi good reviewer,

## Replit online version [here](https://replit.com/@marcooquendoc/CatalogOfMyThings-RubyCapstone#main.rb)

It is a Group project done by:
- Miliyon Ayalew @Miliyonayalew
- Fábio Vinícius Lima @limavfabio 
- Marco Oquendo @MarcoOquendoC 

P and Bob thinking

#### Logic

- Each class from the [UML class diagram](./images/catalog_of_my_things.png) should be created in a separate .rb file.
- All associations (1-to-many relationships) and aggregations (parent-child relationships) between classes should be implemented.
- All properties visible in the diagram should be defined and set up in the constructor method. _Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created._
- All methods visible in the diagram should be implemented:
    - add_item method (in all classes that have that method)
    - can_be_archived?() in all classes

- Add unit tests for all implemented methods.

#### User interface

- Create a main.rb file that will serve as your console app entry-point.
- Your console app, at the start, should:

- The following options are available:
    - List all books
    - List all music albums
    - List of games
    - List all genres (e.g 'Comedy', 'Thriller')
    - List all labels (e.g. 'Gift', 'New')
    - List all authors (e.g. 'Stephen King')
    - Add a book
    - Add a music album
    - Add a game
 - All data should be preserved by saving collections in .json files.

### Database
- Create a schema.sql file with tables that will be analogical to the structure of the classes in your app. As you cannot implement inheritance in the database tables - add all properties and associations from the parent Item class as table columns to all tables based on the child classes. Thanks to that it can be used to store data in the future.

### Project documentation
- A description of the project.
- A demo of the project features.
- Highlight some interesting piece of code or something you built that you are very proud of.
- Make a video describing the project and it features.

### CODE REVIEW

**Review by OLIPLICHE — CHANGES_REQUESTED** [review]
Hi Team, 

Good job so far!
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


## Highlights
- ReadMe is well done 👍 

## Required Changes ♻️

- [x]  Well done for implementing the changes requested by the previous review. Please you need to record the new video and highlight the piece of code which you find proud of making. This was mentioned by my colleague(previous reviewer) and also part of the requirement

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [x] NOTE 👉 **Please push the files of the Project for a better review, tho you have merged the branch by mistake.**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Reem-lab — APPROVED** [review]
# Hi Team, 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🚀🔥🎉🎉 



## Highlights ✨✨
- No Linters errors ✅ 
- Descriptive PR 🚀✅
- Followed Gitflow ✅
- Great working on the functionality and saving the data is JSON files🔥🚀🎉
- Professional README 🔥🚀💯
- Great working on the design in the terminal ✅
- Great working on the presentation video ✅✅



## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Miliyonayalew** [comment]
Thanks @Reem-lab  for the review

**Comment by MarcoOquendoC** [comment]
# Thanks @Reem-lab

**Pull request merged**
